# Generated by Django 5.0.6 on 2024-11-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sede_alter_usuario_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sede',
        ),
        migrations.DeleteModel(
            name='sede',
        ),
    ]
