# Generated by Django 5.0.6 on 2024-11-28 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sedeinstitucion_usuario_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sedeinstitucion'),
        ),
    ]
