# Generated by Django 5.0.6 on 2024-11-28 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usuario_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sedeinstitucion',
            name='id',
        ),
        migrations.AlterField(
            model_name='sedeinstitucion',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sede',
            field=models.ForeignKey(blank=True, db_column='nombre', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sedeinstitucion'),
        ),
    ]
