# Generated by Django 5.0.6 on 2024-11-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_sedeinstitucion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedeinstitucion',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
