# Generated by Django 5.0.6 on 2024-11-28 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sedeinstitucion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sedeinstitucion'),
        ),
    ]
