# Generated by Django 5.0.6 on 2024-11-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_asignatura_usuario_asignaturas_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='asignaturas',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sede',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
        migrations.DeleteModel(
            name='sedeInstitucion',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
