# Generated by Django 5.0.6 on 2024-11-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='asignaturas',
            field=models.ManyToManyField(db_column='nombreAsignatura', related_name='usuarios', to='api.asignatura'),
        ),
    ]
